### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by dguerizec** [livekit/client-sdk-python#12]
Hello,

I'm not sure these need a PR, or separate PRs, so I just list some typos I've found scanning the source with mypy in strict mode.

* Typo in:
https://github.com/livekit/client-sdk-python/blob/db4c5ded64bcfdaeb473537777c9eaa2fd4c0c68/livekit/participant.py#L130
https://github.com/livekit/client-sdk-python/blob/db4c5ded64bcfdaeb473537777c9eaa2fd4c0c68/livekit/track_publication.py#L9
`track` should probably be `_track`, as it seems to be referenced like that throughout the rest of the code.

* Typo in:
https://github.com/livekit/client-sdk-python/blob/db4c5ded64bcfdaeb473537777c9eaa2fd4c0c68/livekit/room.py#L103
It should read `self._close_future.cancelled()`, else it will always evaluate to `True`

* Typo in:
https://github.com/livekit/client-sdk-python/blob/db4c5ded64bcfdaeb473537777c9eaa2fd4c0c68/livekit/track.py#L43
https://github.com/livekit/client-sdk-python/blob/db4c5ded64bcfdaeb473537777c9eaa2fd4c0c68/livekit/track.py#L59
These methods should be marked as `@staticmethod`, because there do not use self, and they are not called on an instance in the example scripts.

**Comment by davidzhao** [comment]
Thank you for pointing this out! We have a PR open that should address point 2 and 3.

I'm still not following what you mean with the first one. Could you clarify?
